#!/Users/geoffreylitt/.rubies/ruby-2.6.3/bin/ruby
# Number all figures in a document and prefix the caption with "Figure".
require "paru/filter"

figure_counter = 0;

Paru::Filter.run do 
    with "Span.html-only" do |div|
      div.inner_markdown = "" unless metadata["format"] == "html" 
    end

    with "Span.pdf-only" do |div|
      div.inner_markdown = "" unless metadata["format"] == "pdf" 
    end

    with "Div.html-only" do |div|
      div.inner_markdown = "" unless metadata["format"] == "html" 
    end

    with "Div.pdf-only" do |div|
      div.inner_markdown = "" unless metadata["format"] == "pdf" 
    end
end